name: iwipe
description: CAP project - Iwipe Cleaning App Training platform
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: '>=3.1.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    flutter_bloc: ^8.1.2
    flutter_screenutil:
    dots_indicator:
    cloud_firestore:
    image_picker: ^1.0.4






    flutter_localizations:
        sdk: flutter
    intl: ^0.18.1
    cupertino_icons: ^1.0.2
    firebase_auth: ^4.9.0
    shared_preferences: ^2.2.1
    permission_handler: ^11.0.0
    firebase_storage: ^11.2.7
    http: ^1.1.0
    flutter_dotenv: ^5.1.0
    flutter_stripe: ^9.4.0
    webview_flutter: 3.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
        - assets/icons/
        - assets/svg/
        - .env
